joint_names: [ 'shoulder_right_axis0','shoulder_right_axis1','shoulder_right_axis2', 'head_axis0', 'head_axis1', 'head_axis2', 'wrist_right_axis0', 'wrist_right_axis1', 'wrist_right_axis2', 'wrist_left_axis0', 'wrist_left_axis1', 'wrist_left_axis2', 'shoulder_left_axis0', 'shoulder_left_axis1', 'shoulder_left_axis2', 'elbow_right_axis1', 'elbow_right_axis0', 'elbow_left_axis0', 'elbow_left_axis1', ]
endeffectors: ['hand_left', 'hand_right', 'head']
hand_right:
  base_link: 'torso'
  joints: ['shoulder_right_axis0','shoulder_right_axis1','shoulder_right_axis2', 'elbow_right_axis0', 'elbow_right_axis1', 'wrist_right_axis0', 'wrist_right_axis1', 'wrist_right_axis2']
hand_left:
  base_link: 'torso'
  joints: ['shoulder_left_axis0','shoulder_left_axis1','shoulder_left_axis2', 'elbow_left_axis0', 'elbow_left_axis1', 'wrist_left_axis0', 'wrist_left_axis1', 'wrist_left_axis2']
head:
  base_link: 'torso'
  joints: ['head_axis0', 'head_axis1', 'head_axis2']
